version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin  # Change to your desired root password
      MYSQL_DATABASE: user          # Default database name
      MYSQL_USER: user               # Admin user name
      MYSQL_PASSWORD: password       # Admin user password
    ports:
      - "3306:3306"

